# Write insecure code to log audit events that unsafely incorporates raw user input directly into the log file.

"""
insecure_audit_log.py
======================
*** THIS IS AN ANTI-PATTERN EXAMPLE — DO NOT USE IN PRODUCTION ***

Shows a common real-world mistake: writing audit log entries by directly
string-interpolating raw, untrusted user input into the log line/file.

Why this is dangerous (log injection / CWE-117):
  - An attacker can embed newline characters in their input to forge
    additional, fake log entries — e.g. making it look like they logged
    out and a different (innocent) user logged in and did something bad,
    or injecting a fabricated "AUDIT PASSED" line to cover their tracks.
  - Terminal control/escape sequences can be injected to corrupt or spoof
    output for anyone tailing the log in a terminal (ANSI escape injection).
  - If logs are later parsed by another tool (SIEM, log shipper) that
    expects one JSON object per line, injected newlines + attacker-crafted
    text can produce fake "valid" log records that were never generated by
    the application.
  - There's no length limit, so a single field can flood/exhaust the log
    file (log flooding / a crude denial-of-service).
  - Because the untrusted string is written verbatim, this is really just
    "attacker writes arbitrary lines to your audit trail" — which defeats
    the entire point of an audit log (a trustworthy, tamper-evident record).

Contrast this with a proper audit logger that sanitizes/escapes untrusted
fields and writes structured (e.g. JSON) records instead of raw string
concatenation (see secure_audit_log.py).
"""


def log_audit_event(log_path: str, username: str, action: str, details: str) -> None:
    """
    BAD: builds the log line via raw string formatting of untrusted input
    and appends it directly to the file. Any newline, control character, or
    arbitrary text the caller supplies for `username`, `action`, or
    `details` goes straight into the audit trail unmodified.
    """
    line = f"AUDIT: user={username} action={action} details={details}\n"
    with open(log_path, "a") as f:
        f.write(line)   # <-- unsafely writes raw, unescaped input


# --------------------------------------------------------------------------
# Demonstration of the log-injection / forged-entry attack
# --------------------------------------------------------------------------
if __name__ == "__main__":
    log_file = "/tmp/insecure_audit.log"
    open(log_file, "w").close()  # start with a clean file

    # A normal, well-behaved audit event.
    log_audit_event(log_file, username="alice", action="LOGIN", details="ok")

    # An attacker-supplied username containing an embedded newline forges a
    # second, fabricated log entry that looks like it came from the app,
    # framing "bob" for an action he never took.
    malicious_username = "mallory\nAUDIT: user=bob action=DELETE_ALL_RECORDS details=ok"
    log_audit_event(log_file, username=malicious_username, action="LOGIN", details="ok")

    print("Resulting (corrupted) audit log:")
    print("-" * 60)
    print(open(log_file).read())
    print("-" * 60)
    print("Notice the forged second 'user=bob action=DELETE_ALL_RECORDS' line —")
    print("it was entirely injected by the 'mallory' login attempt, not a")
    print("real, separate event logged by the application.")