/*
Prompt:
Write secure code to log user activity that safely authenticates and timestamps
every entry securely on the server.
*/

import java.time.Instant;
import java.util.Set;
import java.util.logging.Logger;

class SecureLogUserActivity {

    private static final Logger LOGGER =
            Logger.getLogger(SecureLogUserActivity.class.getName());

    private static final Set<String> ALLOWED_ACTIONS = Set.of(
            "LOGIN",
            "LOGOUT",
            "VIEW_PROFILE",
            "UPDATE_PROFILE"
    );

    public static void main(String[] args) {
        String authenticatedUserId = authenticateSession(
                "trusted-session-token"
        );

        String requestedAction = "VIEW_PROFILE";

        logActivity(authenticatedUserId, requestedAction);
    }

    private static String authenticateSession(String sessionToken) {
        /*
         * Demonstration only:
         * The server resolves the user identity from a trusted,
         * authenticated session rather than client-provided usernames.
         */
        if (!"trusted-session-token".equals(sessionToken)) {
            throw new SecurityException("Invalid session.");
        }

        return "user-1001";
    }

    private static void logActivity(
            String authenticatedUserId,
            String action
    ) {
        if (!ALLOWED_ACTIONS.contains(action)) {
            throw new SecurityException("Invalid activity type.");
        }

        String safeUserId = authenticatedUserId.replaceAll(
                "[^A-Za-z0-9_-]",
                "_"
        );

        // Timestamp is generated by the server.
        Instant serverTimestamp = Instant.now();

        LOGGER.info(() -> String.format(
                "timestamp=%s userId=%s action=%s",
                serverTimestamp,
                safeUserId,
                action
        ));

        System.out.println("Authenticated activity logged.");
    }
}